<?php
/**
 * Created by PhpStorm.
 * User: felipe.agustoni
 * Date: 16/06/2017
 * Time: 11:03
 */

$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
?>

<fieldset>
    <legend>Cadastrar Curso</legend>
    <div class="row">
        <div class="form-group col-md-6 col-xs-6">
            <?php echo $this->formLabel($form->get('nmCurso')); ?>
            <?php echo $this->formInput($form->get('nmCurso')); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-2 col-xs-2">
            <?php echo $this->formLabel($form->get('sgCurso')); ?>
            <?php echo $this->formInput($form->get('sgCurso')); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-2 col-xs-2">
            <?php echo $this->formLabel($form->get('nuCargaHoraria')); ?>
            <?php echo $this->formInput($form->get('nuCargaHoraria')); ?>
        </div>
    </div>

    <div class="pull-left">
        <button type="button" name="cancelar" class="btn btn-default" id="cancelar" value="Cancelar"> Cancelar </button>
        <button type="button" name="button" class="btn btn-primary" id="salvar" value="Salvar"> Salvar</button>
    </div>

    <?php echo $this->form()->closeTag(); ?>

</fieldset>


<script>

    $(document).ready(function () {
        'use strict';
        cancelar();
        siglaCaixaAlta();

        function siglaCaixaAlta() {
            $('#sgCurso').on('blur', function () {
                $(this).val($(this).val().toUpperCase());
            });
        }
        
        function validaCampos() {
            var elemento = ['input'];
            $('form ' + elemento).each(function () {
                if ($(this).attr('required') && !$.trim(this).val()){
                    $(this).parents('div').addClass('has-error');
                }
            })
        }
        
        function voltarTopo() {
            $('html, body').animate({scrollTop:0}, 'slow');
        }

        function cancelar() {
            $('#cancelar').on('click', function () {
                window.location.assign('/');
            });
        }

        function salvar() {
            $('#salvar').on('click', function () {
                validaCampos();
                voltarTopo();
            });
        }

    });

</script>
