<?php
/**
 * Created by PhpStorm.
 * User: felipe.agustoni
 * Date: 19/06/2017
 * Time: 15:22
 */

$form = $this->form;

$form->prepare();
echo $this->form()->openTag($form);
?>

<fieldset>
    <legend>Consultar Curso</legend>
    <div class="row">
        <div class="form-group col-md-6 col-xs-6">
            <?php echo $this->formLabel($form->get('nmCurso')); ?>
            <?php echo $this->formInput($form->get('nmCurso')); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-2 col-xs-2">
            <?php echo $this->formLabel($form->get('sgCurso')); ?>
            <?php echo $this->formInput($form->get('sgCurso')); ?>
        </div>
    </div>

    <div class="pull-left">
        <button type="button" name="cancelar" class="btn btn-default" id="cadastrar" value="Cadastrar"> Cadastrar </button>
        <button type="button" name="button" class="btn btn-primary" id="consultar" value="Consultar"> Consultar</button>
    </div>

    <?php echo $this->form()->closeTag(); ?>

</fieldset>

<script>

    $(document).ready(function () {
       'use strict';
        cadastrar();
        consultarUsuario();

        function cadastrar() {
            $('#cadastrar').on('click', function () {
                window.location.assign('/cadastrar');
            });
        }

        function consultarUsuario() {
            $('#consultar').click(function () {
                $('#divTabelaUsuario').show();
                $('#DadosTabela').DataTable().destroy();
                $('#DadosTabela').DataTable({
                    'searching': false,
                    "pageLength": 10,
                    "language": {
                        "sEmptyTable": "Nenhum registro encontrado para o filtro informado",
                        "sInfo": "Mostrando de START até END de TOTAL registros",
                        "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                        "sInfoFiltered": "(Filtrados de MAX registros)",
                        "sInfoPostFix": "",
                        "sInfoThousands": ".",
                        "sLengthMenu": "_MENU_ resultados por página",
                        "sLoadingRecords": "Carregando...",
                        "sProcessing": "Processando...",
                        "sZeroRecords": "Nenhum registro encontrado",
                        "sSearch": "Pesquisar",
                        "oPaginate": {
                            "sNext": "Próximo",
                            "sPrevious": "Anterior",
                            "sFirst": "Primeiro",
                            "sLast": "Último"
                        },
                        "oAria": {
                            "sSortAscending": ": Ordenar colunas de forma ascendente",
                            "sSortDescending": ": Ordenar colunas de forma descendente"
                        }
                    },
                    "ajax": {
                        url: "/administrativo/curso/consultar",
                        dataType: "JSON",
                        type: "POST",
                        data: {
                            "cpf": $('#nuCpf').val(),
                            "nome": $('#noNome').val(),
                            "estado": $('#coUf').val(),
                            "perfil": $('#coPerfil').val(),
                            "situacao": $("input[name='situacao']:checked").val() ? $("input[name='situacao']:checked").val() : false,
                            "comboPerfil": $('#dadosComboPerfil').val()
                        },
                        dataSrc: ""
                    }
                }
            }
        }

    });

</script>